Atualização do README: repo UserAPI
fga-eps-mds/2022-2-Alectrion-UserAPI pull request #1
Opened 2022-12-06 17:29 UTC by ErickGiffoni

## Modificações

Muda um pouco alguns textos e adiciona os integrantes desse semestre

## _Issue_ relacionado

Resolve parcialmente [#38](https://github.com/fga-eps-mds/2022-2-Alectrion-DOC/issues/38)

## Motivação e Contexto

Modificação necessária para atender ao contexto das diretivas do projeto para o semestre de 2022-2.

## Como foi testado?

Testado com o preview do VsCode.

## Tipo de modificações

- Atualização de documentação

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [x] Atualizei a Documentação

2022-12-09 14:06 UTC, ErickGiffoni commented on README.md
> +feito para atender às demanadas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
```suggestion
feito para atender às demandas da DSTI (Divisão de Suporte Técnico Interno) da Polícia Civil do estado de Goiás.
```

2022-12-09 14:20 UTC, JoaoVitorFarias commented on README.md
> +================================
Acho legal manter o nome dos membros do semestre passado, mas acredito que não precisa manter o readme deles, a informação acaba sendo duplicada.

2022-12-09 14:23 UTC, ErickGiffoni commented on README.md
> +================================
Como assim o readme deles ?

2022-12-11 00:58 UTC, JoaoVitorFarias requested changes

2022-12-11 00:58 UTC, JoaoVitorFarias commented on README.md
> +OBS: Caso for necessario a conexão uma conexão que utilize o SSL, descomentar a linha 7: ```ssl: { rejectUnauthorized: false },``` do arquivo ```src/db/config.ts```
```suggestion
OBS: Caso for necessário a conexão uma conexão que utilize o SSL, descomentar a linha 7: ```ssl: { rejectUnauthorized: false },``` do arquivo ```src/db/config.ts```
```

2022-12-11 00:58 UTC, JoaoVitorFarias commented on README.md
> +================================
é que abaixo da linha 93 as informações estão repetidas, acho que não precisa.

2022-12-11 23:56 UTC, JoaoVitorFarias approved these changes

2022-12-12 00:23 UTC, AlineLermen approved these changes

2022-12-12 00:24 UTC, merged