US 01
fga-eps-mds/2022-2-Alectrion-UserAPI pull request #7
Opened 2023-01-10 01:52 UTC by JoaoVitorFarias

## Descrição
US01

2023-01-12 23:41 UTC, RuanMoura requested changes

2023-01-12 23:41 UTC, RuanMoura commented on report/sonar-report.xml
> +<testCase name="Should teste autentication use case should return an error - password is incorrect" duration="1" />
Remova esse arquivo do PR e adicione ele no .gitignore pls

2023-01-13 01:24 UTC, RuanMoura approved these changes

2023-01-13 12:47 UTC, ErickGiffoni approved these changes
Bora !

2023-01-13 12:47 UTC, merged